import { describe, it, expect, beforeEach } from 'vitest';
import { roundTrip } from './fidelity/round-trip';
import { corpus } from './fidelity/corpus';

// Issue #45 — Milkdown round-trip fidelity gate.
//
// Drives a markdown corpus through Milkdown's parse → edit → serialize cycle
// and asserts AST-equality (not byte-equality) against the source. The point
// is to discover, BEFORE save (#7) lands, which markdown shapes survive a
// round-trip cleanly and which do not — so #7 ships with a known disposition
// (fix / flag-out / accept) for every lossy form rather than discovering loss
// in production.
//
// Why AST-equality, not byte-equality: markdown allows multiple syntactic
// forms for the same semantic (`*foo*` and `_foo_` both render to the same
// emphasis AST). A byte-equality oracle would flag those as failures and
// drown the report in noise. The oracle here parses BOTH the source and
// the serialized output through Milkdown's own parser and compares the
// resulting ProseMirror documents via `Node.eq()` — so any divergence
// flagged is a real loss of meaning, not a normalization choice.

describe('Milkdown round-trip fidelity gate (Issue #45 — AC1)', () => {
  let host: HTMLDivElement;

  beforeEach(() => {
    document.body.innerHTML = '';
    host = document.createElement('div');
    document.body.appendChild(host);
  });

  it('round-trips `# Hello` through the editor with AST-equality', async () => {
    // The minimal smoke case for AC1: a single ATX heading. If the harness
    // returns `equal: false` for `# Hello`, either the harness is broken or
    // Milkdown's commonmark preset has regressed — both are loud failures
    // worth catching at the earliest possible point in the corpus.
    const result = await roundTrip(host, '# Hello');

    expect(
      result.equal,
      `expected AST-equality for the trivial heading case.\nsource:\n${result.source}\nserialized:\n${result.serialized}`,
    ).toBe(true);
  });
});

describe('Milkdown round-trip fidelity gate (Issue #45 — AC2 corpus)', () => {
  // The corpus + harness together pin every markdown shape we know about
  // in v0.2: clean cases assert AST-equality, lossy cases assert
  // INequality. The asymmetric assertion is deliberate — a Milkdown
  // upgrade that fixes a documented-lossy case now fails the test
  // (forcing the disposition report to be updated in the same commit
  // that picks up the fix), and a regression that breaks a documented-
  // clean case also fails (catching the loss before save (#7) ships
  // it to disk).
  //
  // Every `lossy` case must carry a `note` — the report copies it
  // verbatim so the corpus and the report can never drift.

  let host: HTMLDivElement;

  beforeEach(() => {
    document.body.innerHTML = '';
    host = document.createElement('div');
    document.body.appendChild(host);
  });

  for (const c of corpus) {
    it(`${c.category} :: ${c.name} (expected: ${c.expected})`, async () => {
      const result = await roundTrip(host, c.source);

      if (c.expected === 'clean') {
        expect(
          result.equal,
          `${c.category}/${c.name}: documented as 'clean' but did not round-trip cleanly.\n` +
            `Either fix the production wiring (fix-upstream), flag the input out, or update\n` +
            `the disposition to 'lossy' in src/__tests__/fidelity/corpus.ts AND add an entry to\n` +
            `specs/v0.2-mvp-completion/fidelity-report.md.\n` +
            `\n--- source ---\n${c.source}\n--- serialized ---\n${result.serialized}\n`,
        ).toBe(true);
      } else {
        expect(
          result.equal,
          `${c.category}/${c.name}: documented as 'lossy' but now round-trips cleanly.\n` +
            `Update the disposition to 'clean' in src/__tests__/fidelity/corpus.ts AND remove the\n` +
            `entry from specs/v0.2-mvp-completion/fidelity-report.md (the upstream fix worth\n` +
            `celebrating just landed).\n` +
            `\n--- source ---\n${c.source}\n--- serialized ---\n${result.serialized}\n`,
        ).toBe(false);
      }
    });
  }

  it('every `lossy` corpus entry carries a non-empty `note` (so the report can copy it verbatim)', () => {
    // The disposition report is generated by hand in the same commit
    // that adds a lossy case, but the `note` field is the stable
    // contract between the corpus and the report. Without it, the
    // generator/auditor of the report has nothing to anchor on.
    const lossyMissingNotes = corpus.filter(
      (c) => c.expected === 'lossy' && (!c.note || c.note.trim().length === 0),
    );
    expect(
      lossyMissingNotes.map((c) => `${c.category}/${c.name}`),
      'every `lossy` case must declare a `note` (Issue #45 AC2 — used as the report rationale)',
    ).toEqual([]);
  });
});
